{
 "title": "NATS Monitoring",
 "tags": [
  "nats",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnatsd_varz_connections", "type": "series" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnatsd_subsz_num_subscriptions", "type": "series" }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnatsd_varz_in_bytes", "type": "series" }
   ]
  },
  {
   "title": "NATS Connections Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_connections", "legendFormat": "Active Connections", "type": "series" }
   ]
  },
  {
   "title": "JetStream Max Memory Config",
   "type": "timeseries",
   "description": "JetStream Memory Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gnatsd_varz_jetstream_config_max_memory",
     "type": "series"
    }
   ]
  },
  {
   "title": "JetStream Max Storage Config",
   "type": "timeseries",
   "description": "JetStream Storage Usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gnatsd_varz_jetstream_config_max_storage",
     "type": "series"
    }
   ]
  },
  {
   "title": "Messages Throughput",
   "type": "timeseries",
   "description": "Messages Sent/Received",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(gnatsd_varz_out_msgs[1m])", "legendFormat": "Messages Sent/sec" },
    { "expr": "rate(gnatsd_varz_in_msgs[1m])", "legendFormat": "Messages Received/sec" }
   ]
  }
 ]
}